### ISSUE TITLE
您好，请问Rbw旋转矩阵

### ISSUE THREAD

**Issue by boyanghust** [xiaohong-huang/ESKF_9DOF_IMU#1]
#get rotation from world to IMU  ( )
Rbw=Rwb.transpose()
您在文中写的是world to IMU 
请问这个具体含义是
![image](https://user-images.githubusercontent.com/48401445/110791331-0af95e80-82ad-11eb-93c2-1910c955e802.png)
吗  
冒昧方便问一下您的联系方式吗？

**Comment by xiaohong-huang** [comment]
对的。
我的联系方式：
微信:pedro1290265295
qq:1290265295
